### ISSUE TITLE
Notify admin when new User registering on the site.

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/security_tools#8]
To the site administrator, it is important to receive an email notification when a new user registers on the site. My suggestion is to add this feature in the plugin. Thank you.

**Comment by rohit1290** [comment]
Make this optional as many hosting server has mail limit. additionally, once the website is famous the admin would definitely don't want to get a mail every second for new registration.

**Comment by jdalsem** [comment]
Elgg core (3.x) supports admin approval of new users
